# Generated by Django 4.1.2 on 2022-11-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0005_professor_localizacao_habilidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habilidade',
            old_name='professor',
            new_name='owner',
        ),
    ]
