# Generated by Django 4.1.2 on 2022-11-16 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem_perfil', models.ImageField(blank=True, default='professores/user-default.png', null=True, upload_to='alunos/')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('colegio', models.CharField(blank=True, max_length=200, null=True)),
                ('serie', models.CharField(blank=True, max_length=200, null=True)),
                ('dados_responsavel_1', models.TextField(blank=True, null=True)),
                ('dados_responsavel_2', models.TextField(blank=True, null=True)),
                ('dados_nf', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
