# Generated by Django 4.1.2 on 2022-11-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
