# Generated by Django 4.1.2 on 2022-11-02 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_sala_aula_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aulas.pacote'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='aulas.sala'),
        ),
    ]
