# Generated by Django 4.1.2 on 2022-11-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0004_professor_username'),
        ('aulas', '0006_alter_aula_pacote_alter_aula_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='professores.professor'),
        ),
    ]
