# Generated by Django 4.1.2 on 2022-11-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_perfil'),
        ('aulas', '0007_aula_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='alunos.aluno'),
        ),
    ]
